site_title = "MyArxiv"
limit_days = 7
cache_url = "https://Gaetan-007.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"

[[sources]]
limit = 150
category = "cs.AR"
title = "Hardware Architecturea"

[[sources]]
limit = 150
category = "cs.PL"
title = "Programming and Languages"

[[sources]]
limit = 150
category = "cs.OS"
title = "Operation Systems"

[[sources]]
limit = 150
category = "cs.LO"
title = "Logic in Computer Science"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
